# Generated by Django 5.0.3 on 2024-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
